stages:
 data_ingestion:
  cmd: python src/data_ingestion.py
  deps:
  - src/data_ingestion.py
  outs:
  - data/raw
 preprocessing:
  cmd: python src/preprocessing.py
  deps:
  - src/preprocessing.py
  - data/raw
  outs: 
  - data/interim
 model:
  cmd: python src/model.py
  deps:
  - src/model.py
  - data/interim
  - data/raw
  outs:
  - data/output



