stages:

  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - Churn_Modelling.csv
    outs:
      - data/raw

  preprocessing:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/raw
    outs:
      - data/interim

  model:
    cmd: python src/model.py
    deps:
      - src/model.py
      - data/interim
      - data/raw
    outs:
      - data/output/xgb_model.pkl

  evaluation:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/output/xgb_model.pkl
      - data/interim
      - data/raw
    outs:
      - reports/metrics.json
      - reports/predictions.csv
      - reports/confusion_matrix.png
      - reports/threshold.txt
      - reports/threshold_results.csv

  shap:
    cmd: python src/shap_explain.py
    deps:
      - src/shap_explain.py
      - data/output/xgb_model.pkl
      - data/interim
    outs:
      - reports/shap_feature_importance.csv
      - reports/shap_feature_importance.png
      - reports/shap_summary.png